services:
  gpustat-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpustat-web
    restart: unless-stopped
    volumes:
      - ./ssh/known_hosts:/root/.ssh/known_hosts:ro # /path/to/gpustat-web-data/known_hosts:/root/.ssh/known_hosts:ro
      - ./ssh/id_ed25519:/root/.ssh/id_ed25519:ro # /path/to/gpustat-web-data/id_ed25519:/root/.ssh/id_ed25519:ro
    command: ${GPU_HOSTS_OPTION:-} ${GPU_HOSTS}
    # network_mode: 'host'
    environment:
      - GPU_HOSTS=${GPU_HOSTS}
      - GPU_HOSTS_OPTION=${GPU_HOSTS_OPTION}

  caddy:
    image: caddy:2-alpine
    container_name: caddy-gpustat
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-80}:80"
      - "${SSL_PORT:-443}:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data # /path/to/caddy-data/data:/data
      - ./caddy/config:/config # /path/to/caddy-data/config:/config
    environment:
      - CADDY_AUTH_USERNAME=${CADDY_AUTH_USERNAME:-admin}
      - CADDY_AUTH_PASSWORD=${CADDY_AUTH_PASSWORD:-$2a$14$0xVbI0hxgZrq/Lfgb.hVTOWpZ6vF3uCXA9lk5FQJH2L9e.iYVy.4W}
      - SITE_ADDRESS=${SITE_ADDRESS:-localhost}
    # network_mode: 'host'
    depends_on:
      - gpustat-web
